# Generated by Django 5.0.6 on 2024-05-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_actividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('apellido', models.TextField()),
                ('edad', models.IntegerField()),
                ('curso', models.TextField()),
            ],
        ),
    ]
